/**
 * ODINCORE - Authentication Service
 * Handles Firebase Authentication and user profile management
 */

import { auth, db } from './firebase-config.js';
import {
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  signOut,
  onAuthStateChanged,
  setPersistence,
  browserLocalPersistence
} from 'https://www.gstatic.com/firebasejs/11.0.0/firebase-auth.js';
import {
  doc,
  setDoc,
  getDoc,
  collection,
  query,
  where,
  getDocs,
  serverTimestamp
} from 'https://www.gstatic.com/firebasejs/11.0.0/firebase-firestore.js';

// Enable persistent authentication
setPersistence(auth, browserLocalPersistence).catch(err => console.error('Persistence error:', err));

/**
 * Generate unique demo account number
 */
function generateAccountNumber() {
  const prefix = 'ODIN';
  const randomNum = Math.floor(100000000 + Math.random() * 900000000);
  return `${prefix}${randomNum}`;
}

/**
 * Register a new user with Firebase Auth
 */
export async function registerUser(name, email, password) {
  try {
    if (!name || !email || !password) {
      throw new Error('Name, email, and password are required.');
    }

    if (password.length < 8) {
      throw new Error('Password must be at least 8 characters long.');
    }

    // Create Firebase Auth user
    const userCredential = await createUserWithEmailAndPassword(auth, email, password);
    const uid = userCredential.user.uid;

    // Generate unique account number
    const accountNumber = generateAccountNumber();

    // Create user profile in Firestore
    const userRef = doc(db, 'users', uid);
    await setDoc(userRef, {
      uid,
      name,
      email,
      accountNumber,
      role: 'user', // Default role
      accountStatus: 'active',
      initialBalance: 0,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
      lastLogin: null,
      loginCount: 0,
      transferCode: null, // Will be generated by admin
      otpVerified: false,
      kycStatus: 'pending' // KYC = Know Your Customer
    });

    return {
      uid,
      name,
      email,
      accountNumber,
      role: 'user',
      accountStatus: 'active'
    };
  } catch (error) {
    console.error('Registration error:', error);
    if (error.code === 'auth/email-already-in-use') {
      throw new Error('This email is already registered.');
    } else if (error.code === 'auth/weak-password') {
      throw new Error('Password is too weak. Use at least 8 characters.');
    } else if (error.code === 'auth/invalid-email') {
      throw new Error('Invalid email address.');
    }
    throw new Error(error.message || 'Registration failed.');
  }
}

/**
 * Sign in user with email and password
 */
export async function loginUser(email, password) {
  try {
    if (!email || !password) {
      throw new Error('Email and password are required.');
    }

    // Sign in with Firebase Auth
    const userCredential = await signInWithEmailAndPassword(auth, email, password);
    const uid = userCredential.user.uid;

    // Get user profile from Firestore
    const userRef = doc(db, 'users', uid);
    const userSnap = await getDoc(userRef);

    if (!userSnap.exists()) {
      throw new Error('User profile not found. Please contact support.');
    }

    const userProfile = userSnap.data();

    // Check account status
    if (userProfile.accountStatus !== 'active') {
      await signOut(auth);
      throw new Error(`Account is ${userProfile.accountStatus}. Please contact support.`);
    }

    // Update last login
    await setDoc(userRef, {
      lastLogin: serverTimestamp(),
      loginCount: (userProfile.loginCount || 0) + 1,
      updatedAt: serverTimestamp()
    }, { merge: true });

    return userProfile;
  } catch (error) {
    console.error('Login error:', error);
    if (error.code === 'auth/user-not-found') {
      throw new Error('User not found. Please check your email.');
    } else if (error.code === 'auth/wrong-password') {
      throw new Error('Incorrect password.');
    } else if (error.code === 'auth/invalid-email') {
      throw new Error('Invalid email address.');
    }
    throw new Error(error.message || 'Login failed.');
  }
}

/**
 * Sign out current user
 */
export async function logoutUser() {
  try {
    await signOut(auth);
    localStorage.removeItem('odinAuth');
    localStorage.removeItem('odinUser');
    return true;
  } catch (error) {
    console.error('Logout error:', error);
    throw new Error('Logout failed.');
  }
}

/**
 * Get current authenticated user
 */
export function getCurrentAuthUser() {
  return auth.currentUser;
}

/**
 * Listen to auth state changes
 */
export function onAuthStateChange(callback) {
  return onAuthStateChanged(auth, async (user) => {
    if (user) {
      try {
        const userRef = doc(db, 'users', user.uid);
        const userSnap = await getDoc(userRef);
        if (userSnap.exists()) {
          callback({
            ...user,
            profile: userSnap.data()
          });
        } else {
          callback(null);
        }
      } catch (error) {
        console.error('Error fetching user profile:', error);
        callback(null);
      }
    } else {
      callback(null);
    }
  });
}

/**
 * Get user profile by UID
 */
export async function getUserProfile(uid) {
  try {
    const userRef = doc(db, 'users', uid);
    const userSnap = await getDoc(userRef);
    return userSnap.exists() ? userSnap.data() : null;
  } catch (error) {
    console.error('Error fetching user profile:', error);
    throw error;
  }
}

/**
 * Find user by account number
 */
export async function findUserByAccountNumber(accountNumber) {
  try {
    const usersRef = collection(db, 'users');
    const q = query(usersRef, where('accountNumber', '==', accountNumber));
    const querySnapshot = await getDocs(q);
    
    if (querySnapshot.empty) {
      return null;
    }
    
    return querySnapshot.docs[0].data();
  } catch (error) {
    console.error('Error finding user:', error);
    throw error;
  }
}

/**
 * Verify OTP code (admin generates, user verifies)
 */
export async function verifyOTP(uid, otpCode) {
  try {
    const userRef = doc(db, 'users', uid);
    const userSnap = await getDoc(userRef);
    
    if (!userSnap.exists()) {
      throw new Error('User not found.');
    }

    const user = userSnap.data();
    
    // Check if OTP matches (this would be stored by admin)
    if (user.pendingOTP === otpCode) {
      await setDoc(userRef, {
        otpVerified: true,
        pendingOTP: null,
        updatedAt: serverTimestamp()
      }, { merge: true });
      
      return { verified: true, message: 'OTP verified successfully' };
    }

    throw new Error('Invalid OTP code.');
  } catch (error) {
    console.error('OTP verification error:', error);
    throw error;
  }
}

export default {
  registerUser,
  loginUser,
  logoutUser,
  getCurrentAuthUser,
  onAuthStateChange,
  getUserProfile,
  findUserByAccountNumber,
  verifyOTP
};
